---
title: "Standardized Precipitation-Evapotranspiration Index (SPEI)"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
bibliography: ../report/references.bib
csl: ../report/elsevier-harvard.csl
---

```{r setup, include=FALSE}
source("../code/workflowr-utils.R")
```

# Loading the data

```{r read-data}
files = list.files("../data/vector/extraction/", pattern = "_SPEI", full.names = T)

data = lapply(files, function(x){
  filename = str_split(basename(x), "_")[[1]]
  if(length(filename) == 3){
    unit = filename[1]
    buffer = as.numeric(filename[2])
    var = str_remove(filename[3], ".gpkg")
  } else {
    unit = filename[1]
    buffer = 0
    var =  str_remove(filename[2], ".gpkg")
  }
  
  layers = ogrListLayers(x)
  layers = layers[grep("attr_", layers)]
  data = do.call(cbind, lapply(layers, function(l){
    tmp = st_read(x, layer = l, quiet = TRUE)
    lnames = c("SPI1", "SPI3", "SPI6", "SPI12")
    names(tmp) = paste(l, lnames, sep = "-")
    tmp
  }))
  
  data$id = 1:nrow(data)
  data %>%
    as_tibble () %>%
    gather("tmp", "value", -id) %>%
    separate(tmp, into = c("time","SPI"), sep = "-SPI") %>%
    mutate(SPI = as.factor(SPI), 
           time = str_remove(time, "attr_"),
           unit = unit, buffer = buffer, var = var)
})

data = do.call(rbind, data)
str(data)
```

# Missing values

```{r na-analysis}
data %>%
  group_by(unit, buffer) %>%
  summarise(N = n(), isna = sum(is.na(value)), isnotna = sum(!is.na(value)), perc = sum(is.na(value)) / n() * 100)
```

# Time Series


```{r adm-time-series}
data %>%
  filter(buffer==0, unit == "states") %>%
  mutate(time = as.Date(paste0(time, "-01"))) %>%
  group_by(time, unit, SPI) %>%
  summarise(value = median(value, na.rm = T)) %>%
  mutate(sign = if_else(value>0, "pos", "neg"),
         cap = paste0("Scale of ", SPI, " months"),
         scale = as.numeric(as.character(SPI))) %>%
  mutate(cap = fct_reorder(cap, scale, min)) %>%
  ggplot(aes(x=time, y=value, fill = sign)) +
  geom_bar(stat = "identity", show.legend = FALSE) + 
  #scale_x_date(date_breaks = "year", date_labels = "%Y") +
  #scale_y_continuous(breaks = seq(-2, 2, 1)) +
  scale_fill_manual(values = c("#99000d", "#034e7b")) +
  labs(y = "SPI", x = "") +
  theme_classic() +
  facet_wrap(~cap, nrow = 4)

```


```{r bas-time-series}
data %>%
  filter(buffer==0, unit == "basins") %>%
  mutate(time = as.Date(paste0(time, "-01"))) %>%
  group_by(time, unit, SPI) %>%
  summarise(value = median(value, na.rm = T)) %>%
  mutate(sign = if_else(value>0, "pos", "neg"),
         cap = paste0("Scale of ", SPI, " months"),
         scale = as.numeric(as.character(SPI))) %>%
  mutate(cap = fct_reorder(cap, scale, min)) %>%
  ggplot(aes(x=time, y=value, fill = sign)) +
  geom_bar(stat = "identity", show.legend = FALSE) + 
  #scale_x_date(date_breaks = "year", date_labels = "%Y") +
  #scale_y_continuous(breaks = seq(-2, 2, 1)) +
  scale_fill_manual(values = c("#99000d", "#034e7b")) +
  labs(y = "SPI", x = "") +
  theme_classic() +
  facet_wrap(~cap, nrow = 4)

```
